In [1]:
from pyna.polynomial import Poly2d
import numpy as np
c = Poly2d( np.asarray([[2,-1,2], [1,0,0]]), ) * Poly2d( np.asarray([[2,1,], [3,0,]]) )  # one can check this by wolframalpha: (2 - x_2 + 2Power[\(40)x_2\(41),2]+ x_1) * (2+x_2+3*x_1)
c._arr

array([[ 4.,  0.,  3.,  2.],
       [ 8., -2.,  6.,  0.],
       [ 3.,  0.,  0.,  0.]])

In [2]:
c = Poly2d( np.asarray([[2,1], [1,3], [0,-1]]) ) @ (  
    Poly2d(np.asarray([[ 0, 1], [ 2, 1]]), ), 
    Poly2d(np.asarray([[ 0, 3], [-1, 0]]), )   )
c._arr

array([[  2.,   4.,   9.,  -3.],
       [  1.,  16.,  -2.,  -6.],
       [ -6., -11., -10.,  -3.],
       [  4.,   4.,   1.,   0.]])

In [3]:
# one can check this by wolframapha: (2 + y_2 + y_1 + 3 y_1 y_2 - y_1*Power[\(40)y_2\(41),2]); y_1 = x_1 +2x_2 + x_1 x_2 + 2Power[\(40)x_2\(41),2]+3Power[\(40)x_2\(41),3]+3 x_1 Power[\(40)x_2\(41),2]+4 x_1 Power[\(40)x_2\(41),3]; y_2 = -x_2+3x_1+x_1 x_2
c = Poly2d( np.asarray( [[2,1,0], [1,3,-1]] ) ) @ (  Poly2d(np.asarray([[0,2,2,3], [1,1,3,4]])), Poly2d(np.asarray([[0,-1], [3,1]]))   )
c._arr

array([[  2.,   1.,  -4.,  -5., -11.,  -3.],
       [  4.,  17.,  35.,  43.,  16.,   2.],
       [  9.,   0.,   8.,  24.,  22.,   5.],
       [ -9., -15., -34., -55., -27.,  -4.]])

In [4]:
fifth_11 = Poly2d( np.asarray([[0,1,], [1,0,]]) )**5
fifth_11._arr

array([[ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.]])

In [5]:
from pyna.polymap import PolyMap2d

In [6]:
imap = PolyMap2d( 
    Poly2d( np.array([[0,1], [2,1],]), ),
    Poly2d( np.array([[0,3], [1,0],]), ),  ) 

In [7]:
imap2 = imap**2 # (2x+xy, 3y)^3 = (8x + 52xy + 78xy^2 + 27xy^3, 27y)

In [8]:
imap2._cor1poly._arr

array([[0., 5., 3.],
       [5., 9., 3.],
       [2., 1., 0.]])

In [9]:
a = np.arange(12).reshape(3, 4)

In [10]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
np.fliplr(a).diagonal(offset=1)  # Horizontal flip

array([2, 5, 8])

In [11]:
from pyna.polymap import inv_PolyMap2d

In [12]:
invmap = inv_PolyMap2d(imap, tofind_poly_ord=6)

In [17]:
from pyna.polynomial import anti_diagnoal, set_Poly2d_anti_diagnoal
print( anti_diagnoal( invmap._cor1poly._arr, offset=1 ) )
print( anti_diagnoal( invmap._cor2poly._arr, offset=1 ) )
print( anti_diagnoal( invmap._cor1poly._arr, offset=2 ) )
print( anti_diagnoal( invmap._cor2poly._arr, offset=2 ) )

[-0.2  0.6]
[ 0.4 -0.2]
[ 0.048 -0.168  0.072]
[-0.016  0.056 -0.024]


In [19]:
A = np.array([
    anti_diagnoal( invmap._cor1poly._arr, offset=1 )[::-1],
    anti_diagnoal( invmap._cor2poly._arr, offset=1 )[::-1],
]); A

array([[ 0.6, -0.2],
       [-0.2,  0.4]])

In [22]:
eigval, eigvec = LA.eig(A)


In [33]:
V_map = PolyMap2d(
    Poly2d( np.array([[0, eigvec[0,1] ], [ eigvec[0,0], 0]]) ),
    Poly2d( np.array([[0, eigvec[1,1] ], [ eigvec[1,0], 0]]) ),
)
eigvec_inv = LA.inv(eigvec)
V_inv_map = PolyMap2d(
    Poly2d( np.array([[0, eigvec_inv[0,1] ], [ eigvec_inv[0,0], 0]]) ),
    Poly2d( np.array([[0, eigvec_inv[1,1] ], [ eigvec_inv[1,0], 0]]) ),
)

In [39]:
 diag_invmap = V_inv_map @ invmap @ V_map

In [40]:
print( diag_invmap._cor1poly._arr[:3,:3] )
print( diag_invmap._cor2poly._arr[:3,:3] )

[[ 0.          0.         -0.02102924]
 [ 0.7236068  -0.05505528 -0.00122229]
 [ 0.14413659 -0.03548854  0.00295458]]
[[ 0.00000000e+00  2.76393202e-01 -4.96433122e-03]
 [ 5.55111512e-17 -1.29967879e-02 -2.88543821e-04]
 [ 3.40260323e-02 -8.37770877e-03  6.97480824e-04]]


In [42]:
eigval

array([0.7236068, 0.2763932])

In [14]:
idmap = invmap @ imap

$\mathcal{F}: \vec{x} \mapsto \mathrm{A}\vec{x} + \vec{F}^{(2)}(\vec{x}) + \vec{F}^{(3)}(\vec{x}) + \cdots, \vec{x}\in\mathbb{R}^{n}$

We wish to find a coordinate transform to diagonalize the map Jacobian

$\vec{x}=\mathrm{P}\vec{y}$

$\mathcal{F}: \mathrm{P}\vec{y} \mapsto \mathrm{A}\vec{x} + \vec{F}^{(2)}(\vec{x}) + \vec{F}^{(3)}(\vec{x}) + \cdots =\mathrm{A}\mathrm{P}\vec{y} + \vec{F}^{(2)}( \mathrm{P}\vec{y} ) + \vec{F}^{(3)}( \mathrm{P}\vec{y} ) + \cdots , \vec{x}\in\mathbb{R}^{n}$

Left multiplying $\mathrm{P}^{-1}$,

$\mathcal{F}: \vec{y} \mapsto \underbrace{\mathrm{P}^{-1}\mathrm{A}\mathrm{P} }_{\mathrm{\Lambda}(\mathrm{A}) } ~ \vec{y} + \mathrm{P}^{-1}\vec{F}^{(2)}( \mathrm{P}\vec{y} ) + \mathrm{P}^{-1}\vec{F}^{(3)}( \mathrm{P}\vec{y} ) + \cdots , \vec{x}\in\mathbb{R}^{n}$

In fact, $\mathrm{P} = \mathrm{V}$, the eigenvector matrix given by numpy.eig. Hence, $\mathrm{V\Lambda V}^{-1}=\mathrm{A}$.

In [15]:
import numpy as np
from numpy import linalg as LA

Eigenvalues, Eigenvectors = LA.eig(np.array([
        [1, 3],
        [2, 5]
    ]))

Lambda = np.diag(Eigenvalues)


Eigenvectors @ Lambda @ LA.inv(Eigenvectors)

array([[1., 3.],
       [2., 5.]])

In code, the original map is changed by the transform from 

$ \mathcal{F} @ \vec{x}$  

to 

$ \mathrm{P} @ \mathcal{F} @ \mathrm{P}^{-1} @ \vec{x}$. 



In [14]:
Eigenvalues

array([-0.16227766,  6.16227766])

In [129]:
LA.inv(np.array([[2,1], [1,3]]))

array([[ 0.6, -0.2],
       [-0.2,  0.4]])